/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type {
  Interface,
  FunctionFragment,
  DecodedValue,
  Contract,
  BytesLike,
  BigNumberish,
  InvokeFunction,
  BN,
} from "fuels";

import type { Enum, Option } from "./common";

export type OptionInput = Option<[]>;

export type OptionOutput = Option<[]>;

interface ContractsAbiInterface extends Interface {
  functions: {
    test_function: FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "test_function",
    values?: undefined
  ): Uint8Array;

  decodeFunctionData(
    functionFragment: "test_function",
    data: BytesLike
  ): DecodedValue;
}

export class ContractsAbi extends Contract {
  interface: ContractsAbiInterface;
  functions: {
    test_function: InvokeFunction<[], OptionOutput>;
  };
}
